version: '3.7'

services:
  react:
    build:
      context: ./react/xlsx-app/
      dockerfile: Dockerfile
    image: react-xlsx
    container_name: xlsxConverter-React
    ports:
      - "3000:3000"

  spring:
    build:
      context: ./spring/
      dockerfile: Dockerfile
    image: spring-xlsx
    environment:
      - spring.zipfile.path=/XlsxConverter/res/output
      - spring.servlet.multipart.location=/XlsxConverter/res/
      - spring.output.path=output/
    container_name: xlsxConverter-Spring
    ports:
      - "8000:8000"